server:
  port: 8086
  servlet:
    context-path:
mybatis:
  type-aliases-package: com.sixbang.logistics.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/logistics?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
       indent_output: true
    jmx:
      enabled: false #部署多个项目。Tomcat不会发生冲突

logging:
  level:
    org.springframework.security: info
    com.xwm.springboot.mapper: debug

jwt:
  #请求头部的属性
  header: Authorization
    #自定义口令
  secret: mySecret
    #jwt失效时间
  expiration: 1200
    #路由：  /auth 登录路径 /refresh 令牌有失效s时间，刷新令牌的方法路径
  tokenHeader: Bearer
  route:
    authentication:
       path: /auth
       refresh: /refresh